"""eliminamos  USERNAME

Revision ID: 7cb3f88abc0c
Revises: e5cb91424fda
Create Date: 2023-12-13 18:01:20.533011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7cb3f88abc0c'
down_revision = 'e5cb91424fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'service', ['id_service'], ['id'], use_alter=True)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'relationship_user_job', ['id_relationship_user_job'], ['id'], use_alter=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('username')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=20), nullable=False))
        batch_op.create_index('username', ['username'], unique=False)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
