"""tabla

Revision ID: b991def2a397
Revises: bd1aaab75b0a
Create Date: 2023-12-11 02:05:17.183925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b991def2a397'
down_revision = 'bd1aaab75b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('assessment_user_client', sa.Float(), nullable=False),
    sa.Column('comment_user_client', sa.Float(), nullable=False),
    sa.Column('assessment_user_provider', sa.Float(), nullable=False),
    sa.Column('comment_user_provier', sa.Float(), nullable=False),
    sa.Column('state', sa.Enum('canceled', 'evaluate', 'aproved'), nullable=False),
    sa.ForeignKeyConstraint(['id_service'], ['service.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_relationship_user_job', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('date_create', sa.Date(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('attention_time', sa.Date(), nullable=False),
    sa.Column('id_assessment', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('pending', 'in_progress', 'completed'), nullable=False),
    sa.ForeignKeyConstraint(['id_assessment'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['id_relationship_user_job'], ['relationship_user_job.id'], use_alter=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_relationship_user_job', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('attention_day', sa.Date(), nullable=False),
    sa.Column('attention_time', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_relationship_user_job'], ['relationship_user_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    op.drop_table('job_detail')
    op.drop_table('service')
    op.drop_table('assessment')
    # ### end Alembic commands ###
